version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    container_name: flask
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    env_file:
      - ./.envs/.flask
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
