version: "3.9"

volumes:
  local_postgres_data: {}

services:

  django:
    build:
      context: ./stori
      dockerfile: ./compose/local/Dockerfile
    container_name: django_stori
    depends_on:
      - postgres
    volumes:
      - ./stori:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: "postgres:12.3"
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres
