# Generated by Django 3.2.10 on 2022-10-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='oncredit',
            field=models.BooleanField(default=False),
        ),
    ]
